services:
  - type: web
    name: amaneducation
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn amaneducation.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DEBUG
        value: "False"
      - key: DB_HOST
        value: dpg-d89nfsugvqtc73c5v6tg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: db_amaneducation
      - key: DB_USER
        value: db_amaneducation_user
      - key: DB_PASSWORD
        value: 3QkrrTyfGPe4DTWCchQX9y9ldGM6KxFk
      - key: CLOUDINARY_CLOUD_NAME
        value: dyg4401o9
      - key: CLOUDINARY_API_KEY
        value: "489947491336852"
      - key: CLOUDINARY_API_SECRET
        value: ybw_lynZTuhxcRbbQ1NfIVZT9r8
