# Generated by Django 6.0 on 2025-12-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('question_bank', '0002_alter_question_options_alter_question_correct_option_and_more'),
        ('skills', '0002_alter_skill_options_alter_skill_created_at_and_more'),
        ('students', '0002_alter_classroom_options_alter_student_options_and_more'),
        ('teachers', '0002_alter_teacher_options_alter_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'اختبار/تدريب', 'verbose_name_plural': 'الاختبارات والتدريبات'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'محاولة', 'verbose_name_plural': 'محاولات الطالبات'},
        ),
        migrations.AlterModelOptions(
            name='attemptanswer',
            options={'verbose_name': 'إجابة داخل محاولة', 'verbose_name_plural': 'إجابات المحاولات'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('pre', 'اختبار قبلي'), ('post', 'اختبار بعدي'), ('practice', 'تدريب')], max_length=20, verbose_name='نوع التقييم'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.classroom', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='مدة الوقت (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='مفتوح للطالبات؟'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='question_bank.question', verbose_name='الأسئلة'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='skills.skill', verbose_name='المهارة'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='teachers.teacher', verbose_name='المعلمة'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان الاختبار/التدريب'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment', verbose_name='الاختبار/التدريب'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.student', verbose_name='الطالبة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='الدرجة الكاملة'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='chosen_option',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='الإجابة المختارة'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحيحة؟'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.question', verbose_name='السؤال'),
        ),
    ]
