# Generated by Django 6.0 on 2025-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='آمنه مالح العنزي', max_length=200)),
                ('principal_name', models.CharField(blank=True, default='', max_length=200)),
                ('ministry_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('header_line_1', models.CharField(default='المملكة العربية السعودية', max_length=200)),
                ('header_line_2', models.CharField(default='وزارة التعليم', max_length=200)),
                ('header_line_3', models.CharField(default='الإدارة العامة للتعليم بمنطقة الحدود الشمالية', max_length=300)),
                ('header_line_4', models.CharField(default='الثانوية الثالثة عشر بعرعر', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
