# Generated by Django 6.0 on 2025-12-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsettings',
            options={'verbose_name': 'إعدادات المدرسة', 'verbose_name_plural': 'إعدادات المدرسة'},
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='header_line_1',
            field=models.CharField(default='المملكة العربية السعودية', max_length=200, verbose_name='سطر الديباجة 1'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='header_line_2',
            field=models.CharField(default='وزارة التعليم', max_length=200, verbose_name='سطر الديباجة 2'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='header_line_3',
            field=models.CharField(default='الإدارة العامة للتعليم بمنطقة الحدود الشمالية', max_length=300, verbose_name='سطر الديباجة 3'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='header_line_4',
            field=models.CharField(default='الثانوية الثالثة عشر بعرعر', max_length=300, verbose_name='سطر الديباجة 4'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='ministry_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار وزارة التعليم'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='platform_name',
            field=models.CharField(default='آمنه مالح العنزي', max_length=200, verbose_name='اسم المنصة'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='اسم المديرة'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المدرسة'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
