# Generated by Django 6.0 on 2026-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schoolsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsettings',
            options={'verbose_name': 'إعدادات الهوية الرسمية', 'verbose_name_plural': 'إعدادات الهوية الرسمية'},
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='platform_vision',
            field=models.TextField(blank=True, verbose_name='رؤية المنصة (تظهر في التذييل)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#E6E6FA', max_length=7, verbose_name='اللون الأساسي (لافندر)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='show_stats_to_public',
            field=models.BooleanField(default=True, verbose_name='إظهار الإحصاءات العامة للمشرفات'),
        ),
    ]
