# Generated by Django 6.0 on 2026-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهارة/الدرس')),
                ('category', models.CharField(choices=[('QUANT', 'قسم القدرات - كمي'), ('VERBAL', 'قسم القدرات - لفظي'), ('MATH', 'قسم التحصيلي - رياضيات'), ('BIO', 'قسم التحصيلي - أحياء'), ('CHEM', 'قسم التحصيلي - كيمياء'), ('PHYS', 'قسم التحصيلي - فيزياء')], max_length=10, verbose_name='القسم التابع له')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='skills_icons/', verbose_name='أيقونة المهارة (اختياري)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر للبطاقة')),
                ('card_color', models.CharField(default='#2D5A27', max_length=7, verbose_name='لون البطاقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '2. إضافة مهارة/درس',
                'verbose_name_plural': '2. إضافة مهارات ودروس',
            },
        ),
        migrations.AlterModelOptions(
            name='schoolsettings',
            options={'verbose_name': '1. إعدادات الهوية الرسمية', 'verbose_name_plural': '1. إعدادات الهوية الرسمية'},
        ),
    ]
