# Generated by Django 6.0 on 2026-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_alter_schoolsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='developer_name',
            field=models.CharField(default='آمنه مالح العنزي', max_length=200, verbose_name='اسم مبرمجة المنصة'),
        ),
    ]
