# Generated by Django 6.0 on 2026-01-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolsettings_developer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعلمة')),
            ],
            options={
                'verbose_name': '3. أسماء المعلمات',
                'verbose_name_plural': '3. أسماء المعلمات',
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('كمي', 'قسم القدرات - كمي'), ('لفظي', 'قسم القدرات - لفظي'), ('رياضيات', 'قسم التحصيلي - رياضيات'), ('أحياء', 'قسم التحصيلي - أحياء'), ('كيمياء', 'قسم التحصيلي - كيمياء'), ('فيزياء', 'قسم التحصيلي - فيزياء')], max_length=20, verbose_name='القسم التابع له'),
        ),
        migrations.AddField(
            model_name='skill',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='core.teacher', verbose_name='المعلمات المسؤولات'),
        ),
    ]
