# Generated by Django 6.0 on 2026-01-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_alter_skill_category_skill_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'مديرة'), ('TEACHER', 'معلمة'), ('STUDENT', 'طالبة')], default='STUDENT', max_length=10, verbose_name='الدور')),
                ('pin_code', models.CharField(blank=True, max_length=6, verbose_name='رمز التحقق (PIN)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': '4. ملفات المستخدمين',
                'verbose_name_plural': '4. ملفات المستخدمين',
            },
        ),
    ]
