# Generated by Django 6.0 on 2026-01-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='شرح الدرس (كتابة)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_explainer',
            field=models.ImageField(blank=True, null=True, upload_to='skills_images/', verbose_name='صورة توضيحية للشرح'),
        ),
        migrations.AddField(
            model_name='skill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='skills_pdf/', verbose_name='ملف PDF للشرح'),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_questions_count',
            field=models.PositiveIntegerField(default=10, verbose_name='عدد أسئلة الاختبار'),
        ),
        migrations.AddField(
            model_name='skill',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط فيديو (YouTube/Drive)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم المرتبط'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('PRE', 'اختبار قبلي'), ('POST', 'اختبار بعدي')], default='POST', max_length=4, verbose_name='نوع الاختبار')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('option_a', models.CharField(max_length=300, verbose_name='خيار (أ)')),
                ('option_b', models.CharField(max_length=300, verbose_name='خيار (ب)')),
                ('option_c', models.CharField(max_length=300, verbose_name='خيار (ج)')),
                ('option_d', models.CharField(max_length=300, verbose_name='خيار (د)')),
                ('correct_answer', models.CharField(choices=[('A', 'خيار أ'), ('B', 'خيار ب'), ('C', 'خيار ج'), ('D', 'خيار د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('feedback', models.TextField(blank=True, verbose_name='التغذية الراجعة (تظهر في التقرير)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.skill', verbose_name='المهارة/الدرس')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة الاختبارات',
            },
        ),
    ]
