# Generated by Django 6.0 on 2026-01-22 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skill_content_text_skill_image_explainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='التغذية الراجعة (تظهر في التقرير)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=ckeditor.fields.RichTextField(verbose_name='خيار (أ)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=ckeditor.fields.RichTextField(verbose_name='خيار (ب)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=ckeditor.fields.RichTextField(verbose_name='خيار (ج)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=ckeditor.fields.RichTextField(verbose_name='خيار (د)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='content_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرح الدرس (كتابة)'),
        ),
    ]
