# Generated by Django 6.0 on 2026-01-22 11:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_question_feedback_alter_question_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='التغذية الراجعة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='خيار (أ)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='خيار (ب)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='خيار (ج)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='خيار (د)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='content_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرح الدرس (كتابة)'),
        ),
    ]
