# Generated by Django 5.1 on 2026-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_question_feedback_alter_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='رقم الهوية'),
        ),
    ]
