# Generated by Django 5.2.14 on 2026-05-25 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='ministry_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار وزارة التعليم'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار المدرسة'),
        ),
    ]
