# Generated by Django 5.2.14 on 2026-05-26 07:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cloudinary_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='أيقونة المهارة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image_explainer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة توضيحية للشرح'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ملف PDF للشرح'),
        ),
    ]
