# Generated by Django 6.0 on 2025-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
            ],
        ),
    ]
