# Generated by Django 6.0 on 2025-12-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailystat',
            options={'ordering': ['-date'], 'verbose_name': 'إحصائية يومية', 'verbose_name_plural': 'الإحصاءات اليومية'},
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='avg_score',
            field=models.FloatField(default=0, verbose_name='متوسط الدرجة'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='date',
            field=models.DateField(unique=True, verbose_name='التاريخ'),
        ),
    ]
