# Generated by Django 6.0 on 2025-12-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_access', '0001_initial'),
        ('skills', '0002_alter_skill_options_alter_skill_created_at_and_more'),
        ('students', '0002_alter_classroom_options_alter_student_options_and_more'),
        ('teachers', '0002_alter_teacher_options_alter_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسة دخول عبر QR', 'verbose_name_plural': 'جلسات الدخول عبر QR'},
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='students.classroom', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='تاريخ ووقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الجلسة مفعّلة'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='skills.skill', verbose_name='المهارة'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='teachers.teacher', verbose_name='المعلمة'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='token',
            field=models.CharField(max_length=64, unique=True, verbose_name='رمز الجلسة'),
        ),
    ]
