# Generated by Django 5.1 on 2026-04-17 13:28

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options_alter_teacher_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('pre', 'اختبار قبلي'), ('post', 'اختبار بعدي'), ('lesson', 'اختبار درس تحصيلي'), ('bank', 'اختبار من بنك الأسئلة')], max_length=10, verbose_name='نوع الاختبار')),
                ('questions_count', models.PositiveIntegerField(default=10, verbose_name='عدد الأسئلة')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='مدة الاختبار (دقيقة)')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='درجة النجاح %')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('delivery', models.CharField(choices=[('electronic', 'إلكتروني فقط'), ('paper', 'ورقي فقط'), ('both', 'إلكتروني + ورقي')], default='both', max_length=15, verbose_name='طريقة التسليم')),
                ('correction', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي'), ('both', 'كلاهما')], default='auto', max_length=10, verbose_name='طريقة التصحيح')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّل')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='ترتيب عشوائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة')),
                ('total', models.PositiveIntegerField(default=10, verbose_name='الدرجة الكاملة')),
                ('percentage', models.FloatField(default=0, verbose_name='النسبة %')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجحة')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, verbose_name='الوقت المستغرق (ثانية)')),
                ('manually_corrected', models.BooleanField(default=False, verbose_name='صُحّح يدوياً')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_results', to='teachers.teacher', verbose_name='صحّحتها')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_exam_results', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teachers.teacherexam', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TeacherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_skill_name', models.CharField(blank=True, max_length=200, verbose_name='المهارة المستهدفة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='نص السؤال (مع رموز)')),
                ('question_plain', models.TextField(blank=True, verbose_name='نص السؤال البسيط')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='صورة السؤال')),
                ('option_a', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='خيار أ')),
                ('option_b', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='خيار ب')),
                ('option_c', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='خيار ج')),
                ('option_d', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='خيار د')),
                ('option_a_plain', models.CharField(blank=True, max_length=500, verbose_name='خيار أ (نص)')),
                ('option_b_plain', models.CharField(blank=True, max_length=500, verbose_name='خيار ب (نص)')),
                ('option_c_plain', models.CharField(blank=True, max_length=500, verbose_name='خيار ج (نص)')),
                ('option_d_plain', models.CharField(blank=True, max_length=500, verbose_name='خيار د (نص)')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('feedback', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='تغذية راجعة')),
                ('feedback_plain', models.TextField(blank=True, verbose_name='تغذية راجعة بسيطة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teachers.teacherexam', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(max_length=1, verbose_name='الإجابة المختارة')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيحة')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.examresult', verbose_name='النتيجة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة طالبة',
                'verbose_name_plural': 'إجابات الطالبات',
            },
        ),
        migrations.CreateModel(
            name='TeacherSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('skill', 'مهارة قدرات'), ('lesson', 'درس تحصيلي'), ('bank', 'بنك أسئلة')], default='skill', max_length=10, verbose_name='نوع المحتوى')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('skill_type', models.CharField(blank=True, choices=[('qodrat_kamy', 'قدرات — كمي'), ('qodrat_lafzy', 'قدرات — لفظي')], max_length=20, verbose_name='نوع القدرات')),
                ('subject', models.CharField(blank=True, choices=[('math', 'تحصيلي — رياضيات'), ('bio', 'تحصيلي — أحياء'), ('chem', 'تحصيلي — كيمياء'), ('phys', 'تحصيلي — فيزياء')], max_length=10, verbose_name='مادة التحصيلي')),
                ('description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('target_classes', models.CharField(blank=True, help_text='مثال: ث١٢,ث١١', max_length=100, verbose_name='الفصول المستهدفة')),
                ('is_shared', models.BooleanField(default=True, verbose_name='مشاركة مع المعلمات')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_skills', to='teachers.teacher', verbose_name='المعلمة المنشئة')),
            ],
            options={
                'verbose_name': 'مهارة / درس',
                'verbose_name_plural': 'المهارات والدروس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.teacherskill', verbose_name='المهارة/الدرس'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('qodrat', 'قدرات'), ('tahsili', 'تحصيلي'), ('both', 'قدرات + تحصيلي')], default='qodrat', max_length=10, verbose_name='نوع الحصة')),
                ('target_class', models.CharField(max_length=50, verbose_name='الفصل المستهدف')),
                ('session_date', models.DateField(verbose_name='تاريخ الحصة')),
                ('session_time', models.TimeField(verbose_name='وقت الحصة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teachers.teacher', verbose_name='المعلمة')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='teachers.teacherexam', verbose_name='الاختبار المفعّل')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teachers.teacherskill', verbose_name='المهارة/الدرس')),
            ],
            options={
                'verbose_name': 'سجل حصة',
                'verbose_name_plural': 'سجل الحصص',
                'ordering': ['-session_date', '-session_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSkillContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرح نصي (مع رموز ومعادلات)')),
                ('plain_text', models.TextField(blank=True, verbose_name='شرح نصي بسيط')),
                ('plain_image', models.ImageField(blank=True, null=True, upload_to='skill_content/', verbose_name='صورة توضيحية')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط فيديو')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='skill_pdfs/', verbose_name='ملف PDF')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='teachers.teacherskill', verbose_name='المهارة/الدرس')),
            ],
            options={
                'verbose_name': 'محتوى الشرح',
            },
        ),
    ]
