# Generated by Django 5.1 on 2026-04-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherexam_examresult_teacherquestion_studentanswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherskillcontent',
            options={'verbose_name': 'محتوى الشرح', 'verbose_name_plural': 'محتوى الشروح'},
        ),
    ]
