# Generated by Django 5.1 on 2026-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacherskillcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherexam',
            name='exam_type',
            field=models.CharField(choices=[('pre', 'اختبار قبلي'), ('post', 'اختبار بعدي'), ('lesson', 'اختبار درس تحصيلي'), ('bank', 'اختبار من بنك الأسئلة'), ('comprehensive_qodrat', 'اختبار شامل — قدرات'), ('comprehensive_tahsili', 'اختبار شامل — تحصيلي')], max_length=30, verbose_name='نوع الاختبار'),
        ),
        migrations.AlterField(
            model_name='teacherskill',
            name='content_type',
            field=models.CharField(choices=[('skill', 'مهارة قدرات'), ('lesson', 'درس تحصيلي'), ('bank', 'بنك أسئلة'), ('comprehensive', 'اختبار شامل')], default='skill', max_length=20, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='teacherskill',
            name='target_classes',
            field=models.CharField(blank=True, max_length=100, verbose_name='الفصول المستهدفة'),
        ),
    ]
