# Generated by Django 6.0 on 2026-05-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_classroom_options_alter_student_options_and_more'),
        ('teachers', '0006_option_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='الطالبة (سجل)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.classroom', verbose_name='الفصول'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_exam_results', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة (حساب)'),
        ),
    ]
