# Generated by Django 5.2.14 on 2026-05-26 07:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_examresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='option_a_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة خيار أ'),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='option_b_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة خيار ب'),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='option_c_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة خيار ج'),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='option_d_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة خيار د'),
        ),
        migrations.AlterField(
            model_name='teacherquestion',
            name='question_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة السؤال'),
        ),
        migrations.AlterField(
            model_name='teacherskillcontent',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ملف PDF'),
        ),
        migrations.AlterField(
            model_name='teacherskillcontent',
            name='plain_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة توضيحية'),
        ),
    ]
