# Generated by Django 5.2.14 on 2026-06-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teacherquestion_option_a_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquestion',
            name='target_skill_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='المهارة المستهدفة (نص حر — قديم)'),
        ),
        migrations.CreateModel(
            name='SkillStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('qodrat_kamy', 'قدرات — كمي'), ('qodrat_lafzy', 'قدرات — لفظي'), ('tahsili_math', 'تحصيلي — رياضيات'), ('tahsili_bio', 'تحصيلي — أحياء'), ('tahsili_chem', 'تحصيلي — كيمياء'), ('tahsili_phys', 'تحصيلي — فيزياء')], max_length=20, verbose_name='المسار')),
                ('code', models.CharField(help_text='مثل: QK01, QL05, TM03', max_length=20, unique=True, verbose_name='رمز المهارة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهارة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المهارة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='teachers.skillstandard', verbose_name='المهارة الأم (اختياري)')),
            ],
            options={
                'verbose_name': 'مهارة معيارية',
                'verbose_name_plural': 'المهارات المعيارية',
                'ordering': ['track', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='teacherquestion',
            name='skill_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='teachers.skillstandard', verbose_name='المهارة المعيارية'),
        ),
    ]
