# Generated by Django 6.0 on 2025-12-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_options_alter_attempt_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقرير', 'verbose_name_plural': 'التقارير'},
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='assessments.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التقرير'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='صورة التقرير'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='ملف التقرير (PDF)'),
        ),
    ]
