# Generated by Django 6.0 on 2025-12-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('qudurat', 'قدرات'), ('tahsili', 'تحصيلي')], default='qudurat', max_length=20)),
                ('section', models.CharField(choices=[('verbal', 'لفظي'), ('quant', 'كمي'), ('math', 'رياضيات'), ('bio', 'أحياء'), ('chem', 'كيمياء'), ('phys', 'فيزياء')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='teachers.teacher')),
            ],
            options={
                'ordering': ['track', 'section', 'title'],
            },
        ),
    ]
