# Generated by Django 6.0 on 2025-12-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('teachers', '0002_alter_teacher_options_alter_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['track', 'section', 'title'], 'verbose_name': 'مهارة', 'verbose_name_plural': 'المهارات'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='وصف المهارة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّلة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.CharField(choices=[('verbal', 'لفظي'), ('quant', 'كمي'), ('math', 'رياضيات'), ('bio', 'أحياء'), ('chem', 'كيمياء'), ('phys', 'فيزياء')], max_length=20, verbose_name='القسم / المادة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='teacher_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='teachers.teacher', verbose_name='المعلمة المسؤولة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=250, verbose_name='اسم المهارة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='track',
            field=models.CharField(choices=[('qudurat', 'قدرات'), ('tahsili', 'تحصيلي')], default='qudurat', max_length=20, verbose_name='المسار'),
        ),
    ]
