# Generated by Django 6.0 on 2025-12-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('skills', '0002_alter_skill_options_alter_skill_created_at_and_more'),
        ('students', '0002_alter_classroom_options_alter_student_options_and_more'),
        ('teachers', '0002_alter_teacher_options_alter_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'درس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.classroom', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='محتوى الدرس (يدعم LaTeX)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exported_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lessons/', verbose_name='ملف الدرس (PDF)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='skills.skill', verbose_name='المهارة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.teacher', verbose_name='المعلمة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان الدرس'),
        ),
    ]
